name: side_menu_animation
description: Animated Side Menu with customizable UI. Inspired in Yalantis library (Android/iOS).
version: 0.0.2
homepage: https://www.diegoveloper.com
repository: https://github.com/diegoveloper/flutter_side_menu_animation/

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: